title: Kelly Rangel # your name (or website title) here
logo: "images/Screen Shot 2023-02-11 at 11.47.10 AM.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst, Data Visualization, Applied Mathematics Graduate <br>
  <br>
  Learn about my projects using Excel, Tableau, SQL, and Python <br>

Let's Connect: <br>
  - <a href="https://www.linkedin.com/in/kellyjrangel/">My LinkedIn </a> <br>
  - <a href="https://public.tableau.com/app/profile/kelly.rangel">My Tableau Public</a><br>
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
